from api.models import Place

places = [
    {"name": "Coffeemania", "description": "Cozy coffee shop in the heart of the city with warm atmosphere and great espresso.", "place_type": "coffee_shop", "location": "Almaty, Dostyk Ave 10", "budget": "medium", "mood": "cozy", "image_url": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=740"},
    {"name": "Romantique", "description": "Elegant French restaurant perfect for a special evening with candles and live music.", "place_type": "restaurant", "location": "Almaty, Abay Ave 52", "budget": "high", "mood": "romantic", "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=740"},
    {"name": "Central Park", "description": "Beautiful city park with fountains, walking paths and peaceful scenery.", "place_type": "park", "location": "Almaty, Panfilov St 1", "budget": "low", "mood": "calm", "image_url": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=740"},
    {"name": "IMAX Cinema", "description": "Modern cinema with IMAX screen and comfortable seats for a great movie night.", "place_type": "cinema", "location": "Almaty, Mega Park Mall", "budget": "medium", "mood": "fun", "image_url": "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=740"},
    {"name": "Cafe Velvet", "description": "Trendy cafe with vintage decor, handcrafted drinks and homemade pastries.", "place_type": "cafe", "location": "Almaty, Zhibek Zholy 23", "budget": "medium", "mood": "cozy", "image_url": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=740"},
    {"name": "Sky Lounge", "description": "Rooftop restaurant with panoramic views of the city and fine dining experience.", "place_type": "restaurant", "location": "Almaty, Nurly Tau Tower", "budget": "high", "mood": "romantic", "image_url": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=740"},
    {"name": "Brew Lab", "description": "Specialty coffee lab where baristas craft unique single-origin pour-overs.", "place_type": "coffee_shop", "location": "Almaty, Gogol St 78", "budget": "medium", "mood": "cozy", "image_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=740"},
    {"name": "Garden Bistro", "description": "Outdoor restaurant surrounded by greenery, serving fresh Mediterranean cuisine.", "place_type": "restaurant", "location": "Almaty, Al-Farabi Ave 17", "budget": "medium", "mood": "romantic", "image_url": "https://images.unsplash.com/photo-1592861956120-e524fc739696?w=740"},
    {"name": "Kok-Tobe Park", "description": "Mountain park accessible by cable car with stunning views of Almaty.", "place_type": "park", "location": "Almaty, Kok-Tobe Hill", "budget": "low", "mood": "romantic", "image_url": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=740"},
    {"name": "Cineplex VIP", "description": "Premium cinema with VIP recliner seats, gourmet snacks and private screenings.", "place_type": "cinema", "location": "Almaty, Esentai Mall", "budget": "high", "mood": "fun", "image_url": "https://images.unsplash.com/photo-1595769816263-9b910be24d5f?w=740"},
    {"name": "Morning Glory Cafe", "description": "Bright and cheerful breakfast cafe with all-day brunch menu and fresh juices.", "place_type": "cafe", "location": "Almaty, Seifullin Ave 5", "budget": "low", "mood": "fun", "image_url": "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=740"},
    {"name": "La Terrasse", "description": "Sophisticated French cafe with outdoor terrace, macarons and champagne.", "place_type": "cafe", "location": "Almaty, Dostyk Ave 36", "budget": "high", "mood": "romantic", "image_url": "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=740"},
    {"name": "Sushi Garden", "description": "Japanese restaurant with zen garden interior and premium omakase menu.", "place_type": "restaurant", "location": "Almaty, Timiryazev St 42", "budget": "high", "mood": "calm", "image_url": "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=740"},
    {"name": "Botanic Garden", "description": "Peaceful botanical garden with thousands of plant species and quiet walking paths.", "place_type": "park", "location": "Almaty, Timiryazev St 1", "budget": "low", "mood": "calm", "image_url": "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=740"},
    {"name": "Darkroom Cinema", "description": "Art-house cinema showing indie films with a cozy bar inside.", "place_type": "cinema", "location": "Almaty, Furmanov St 60", "budget": "low", "mood": "cozy", "image_url": "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=740"},
    {"name": "The Rustic Cup", "description": "Warm coffee shop with exposed brick walls, board games and comfy armchairs.", "place_type": "coffee_shop", "location": "Almaty, Kabanbay Batyr 12", "budget": "low", "mood": "cozy", "image_url": "https://images.unsplash.com/photo-1493857671505-72967e2e2760?w=740"},
    {"name": "Taste of Asia", "description": "Vibrant Asian fusion restaurant with bold flavors and lively atmosphere.", "place_type": "restaurant", "location": "Almaty, Rozybakiev St 8", "budget": "medium", "mood": "fun", "image_url": "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=740"},
    {"name": "Sunset Park", "description": "Open park by the river with sunset views, bike rentals and picnic areas.", "place_type": "park", "location": "Almaty, Ile River Embankment", "budget": "low", "mood": "fun", "image_url": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=740"},
    {"name": "Neon Cinema", "description": "Modern multiplex with 3D and 4DX screens and a huge popcorn selection.", "place_type": "cinema", "location": "Almaty, Khan Shatyr Mall", "budget": "medium", "mood": "fun", "image_url": "https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=740"},
    {"name": "Casa Blanca", "description": "Mediterranean restaurant with white interior, sea bass and sangria.", "place_type": "restaurant", "location": "Almaty, Bogenbay Batyr 101", "budget": "high", "mood": "romantic", "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=740"},
    {"name": "Zen Coffee", "description": "Minimalist Japanese-style coffee shop with matcha lattes and tranquil music.", "place_type": "coffee_shop", "location": "Almaty, Masanchi St 99", "budget": "medium", "mood": "calm", "image_url": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=740"},
    {"name": "Gorky Park", "description": "Classic city park with rides, open-air stage and weekend food festivals.", "place_type": "park", "location": "Almaty, Gogol St 1", "budget": "low", "mood": "fun", "image_url": "https://images.unsplash.com/photo-1455763916899-e8b50eca9967?w=740"},
    {"name": "The Loft Cafe", "description": "Industrial-style loft cafe with high ceilings, craft beer and DJs on weekends.", "place_type": "cafe", "location": "Almaty, Shevchenko St 44", "budget": "medium", "mood": "fun", "image_url": "https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?w=740"},
    {"name": "Hidden Garden", "description": "Secret garden restaurant hidden in a courtyard, serving seasonal farm-to-table dishes.", "place_type": "restaurant", "location": "Almaty, Zenkova St 15", "budget": "high", "mood": "calm", "image_url": "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=740"},
    {"name": "Moonlight Coffee", "description": "Late-night coffee shop open until 3am with fairy lights and acoustic live music.", "place_type": "coffee_shop", "location": "Almaty, Tulebaev St 33", "budget": "medium", "mood": "romantic", "image_url": "https://images.unsplash.com/photo-1507914464562-6ff4b11e4e52?w=740"},
]

created = 0
for p in places:
    Place.objects.get_or_create(name=p["name"], defaults=p)
    created += 1
    print(f"✓ {p['name']}")

print(f"\nDone! {created} places added.")
