# Generated by Django 5.2.13 on 2026-04-21 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('place_type', models.CharField(choices=[('cafe', 'Cafe'), ('restaurant', 'Restaurant'), ('cinema', 'Cinema'), ('park', 'Park'), ('coffee_shop', 'Coffee Shop')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('budget', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('mood', models.CharField(choices=[('romantic', 'Romantic'), ('cozy', 'Cozy'), ('fun', 'Fun'), ('calm', 'Calm')], max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.place')),
            ],
            options={
                'unique_together': {('user', 'place')},
            },
        ),
    ]
